name: Generate Reference
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1.2.0

      # Terraform Init required before terraform-docs
      - name: Terraform Init
        id: init
        run: terraform init -backend=false -lock=false

    - name: Render Reference with terraform-docs
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: .
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'
